### ISSUE TITLE
e-Asia Digital Library (easia)

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#120]
**Item Count:** 4049 items

**Item Types:** Image/Document/Audio/Video

**Access Restrictions:** 1 item

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/easia
lists generated 20220624

**Comment by lsat12357** [comment]
exported 20220626

**Comment by lharka** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 
- [ ] Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are appearing for works; the collection has the correct icon.
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 
- Confirm copyright logo matches statement

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve (step 11)

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by lharka** [comment]
Post-migration remediation work needed:
Some items display repetition within the field (text repeats). This issue is inherited from the OD1 asset (metadata is identical). Examples:
- https://prod.oregondigital.org/concern/images/df72d035g#content
- https://prod.oregondigital.org/concern/images/df72cw94v?locale=en#content
- https://prod.oregondigital.org/concern/documents/df72cx38q?locale=en#content
- https://prod.oregondigital.org/concern/images/df72d024z?locale=en#content
- https://prod.oregondigital.org/concern/images/df72d0770?locale=en#content
- https://prod.oregondigital.org/concern/images/df72cv72m?locale=en#content

**Comment by lharka** [comment]
Almost complete. To review: 45 audio assets

**Comment by lharka** [comment]
@lsat12357 Stalled batches due to audio file problems (mpegs, no derivatives created)

**Comment by lsat12357** [comment]
Sorry, thought I'd fixed the audio files, but evidently I only did uo-veterans. Fixed now, as in the duration has been added to the file metadata so that the player works. Because the files are actually there, verification doesn't flag these. 
Remaining issue: minimagick problems with filesets in ac, ae, and af are documented in those tickets.

**Comment by sseymore** [comment]
I moved tickets for 3 batches mentioned above to the stall queue. Comments for @lsat12357 to clarify errors in plain language for us to remediate.

**Comment by lsat12357** [comment]
um, are you asking me about the remediation request? that was Leslie

**Comment by sseymore** [comment]
@sarahfish07 Can you pick up QA for this collection? It needs QA of 5 audio files only: 

https://prod.oregondigital.org/catalog?f%5Bfile_format_sim%5D%5B%5D=mpeg+%28MPEG+1%2F2+Audio+Layer+3%29&f%5Bnon_user_collections_ssim%5D%5B%5D=easia&locale=en

and quick spot check of the rest. Let me know if you have questions.

**Comment by sseymore** [comment]
https://prod.oregondigital.org/concern/documents/df72cx497#content viewer still failing

**Comment by sarahfish07** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 
- [ ] Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are appearing for works; the collection has the correct icon.
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 
- Confirm copyright logo matches statement

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve (step 11)

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by sseymore** [comment]
Creator Display is a free text field.

@lsat12357 can you look at the UV for these works? Mostly audio issues.

**Comment by lsat12357** [comment]
I tried clicking on a few of the audio assets, and they are working for me. I tried my latest fixes on one the 3 pdfs (I rewrote using ghostscript, deleted the fileset, reattached the file, then reindexed.)  and am not having any luck. they may have to stay borked until I can come up with something else to try. Perhaps sarahfish07 could research pdf tools and experiment on staging?

**Comment by sarahfish07** [comment]
@lsat12357 Audio is also working for me. I will research pdf tools and see what I can figure out for the images.

**Comment by sseymore** [comment]
@lsat12357 we don't know what's going on with these PDFs... bulk approve the rest of the collection except these works? Not sure what else to do. Will chat with you on Teams.

**Comment by lsat12357** [comment]
please doublecheck this, I deleted the problem pdf assets and redid them with the jpg derivatives downloaded from OD1. I thought I recast them as images, but somehow, they're still in the system as documents?? so the links above work. Please confirm that I grabbed the correct images and matched them with the right OD2 resources. These are completely wacko, and I am fine with revisiting them in case you are not happy about preservation concerns, just not today.

**Comment by sseymore** [comment]
@lsat12357 I checked the 3 works above with the OD1 works and all looks good to me! 

QA pass, moving to bulk review

**Comment by sarahfish07** [comment]
URIs that need to be fixed:
[http://opaquenamespace.org/ns/subject/MaoZedongThought](https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=easia&f%5Btopic_combined_label_sim%5D%5B%5D=http%3A%2F%2Fopaquenamespace.org%2Fns%2Fsubject%2FMaoZedongThought&locale=en) 137 works
[http://opaquenamespace.org/ns/subject/PeoplesRepublic1949](https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=easia&f%5Btopic_combined_label_sim%5D%5B%5D=http%3A%2F%2Fopaquenamespace.org%2Fns%2Fsubject%2FPeoplesRepublic1949&locale=en) 81 works
[http://opaquenamespace.org/ns/subject/LanguagelearningTaiwan](https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=easia&f%5Btopic_combined_label_sim%5D%5B%5D=http%3A%2F%2Fopaquenamespace.org%2Fns%2Fsubject%2FLanguagelearningTaiwan&locale=en) 50 works
[http://opaquenamespace.org/ns/subject/ChinaInternationalRelations](https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=easia&f%5Btopic_combined_label_sim%5D%5B%5D=http%3A%2F%2Fopaquenamespace.org%2Fns%2Fsubject%2FChinaInternationalRelations&locale=en) 44 works
[http://opaquenamespace.org/ns/subject/FairytalesfolkloremythologyJapan](https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=easia&f%5Btopic_combined_label_sim%5D%5B%5D=http%3A%2F%2Fopaquenamespace.org%2Fns%2Fsubject%2FFairytalesfolkloremythologyJapan&locale=en) 37 works
[http://opaquenamespace.org/ns/subject/PoetryJapan](https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=easia&f%5Btopic_combined_label_sim%5D%5B%5D=http%3A%2F%2Fopaquenamespace.org%2Fns%2Fsubject%2FPoetryJapan&locale=en) 24 works
[http://opaquenamespace.org/ns/subject/KoreaNorthInternationalRelations](https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=easia&f%5Btopic_combined_label_sim%5D%5B%5D=http%3A%2F%2Fopaquenamespace.org%2Fns%2Fsubject%2FKoreaNorthInternationalRelations&locale=en) 23 works

**Comment by lsat12357** [comment]
it's looking like the opaquenamespace uris don't exist yet

**Comment by sarahfish07** [comment]
All URIs fixed. 
This page doesn’t open: https://oregondigital.org/concern/documents/df72d539m

**Comment by sarahfish07** [comment]
Fixed publication place, publisher, description, is part of, titles, creator display.
QA'ed. No other errors found (except the page that won't open, noted above).

**Comment by sarahfish07** [comment]
Copyright updated for 1928.
